"""init schema

Revision ID: 20cc3ae37118
Revises: 
Create Date: 2025-10-26 12:39:51.898822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cc3ae37118'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etlrun',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_ingested', sa.Integer(), nullable=False),
    sa.Column('error_text', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_etlrun'))
    )
    op.create_table('rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base', sa.String(length=10), nullable=False),
    sa.Column('quote', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate')),
    sa.UniqueConstraint('date', 'base', 'quote', 'source', name='uq_rates_bq_date_src')
    )
    op.create_index(op.f('ix_rate_base'), 'rate', ['base'], unique=False)
    op.create_index(op.f('ix_rate_date'), 'rate', ['date'], unique=False)
    op.create_index(op.f('ix_rate_quote'), 'rate', ['quote'], unique=False)
    op.create_table('symbol',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_symbol'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symbol')
    op.drop_index(op.f('ix_rate_quote'), table_name='rate')
    op.drop_index(op.f('ix_rate_date'), table_name='rate')
    op.drop_index(op.f('ix_rate_base'), table_name='rate')
    op.drop_table('rate')
    op.drop_table('etlrun')
    # ### end Alembic commands ###
